

to_publish = Hash.new
publish_metadata = Hash.new

releases_data = nil
from_publish_store = false



## key is `deliver`'s identifier, value is matching resolution
devices_ios_resolution = {
  IPHONE_55: "414x736x3",
  IPHONE_65: "414x896x3",
  IPHONE_67: "430x932x3",
  IPAD_PRO_129: "1024x1366x2",
  IPAD_PRO_3GEN_129: "1024x1366x2"
}

devices_android_resolution = {
  phone: "375x667x2",
  sevenInch: "1080x810x2",
  tenInch: "1800x1200x2",
}


desc "Produce final bundled javascript and css"
private_lane :build_web_pack do |options|
  Dir.chdir(Actions.lane_context[SharedValues::SANDBOX_PATH]) do
    sh "npm ci"
    FileUtils.mkdir_p("public/i18n")
    sh "npm run gettext:compile"
    sh "npm run build"
    sh "touch .built-web-pack"
  end
end


desc "Parse options and define precise targets (app and version)"
private_lane :_setup_targets do |options|
  apps = options[:app]
  releases_data = load_releases_data unless releases_data
  if apps != "monujo"
    apps = apps.split(",") if apps
    apps = releases_data.keys unless apps
  else
    apps = ["monujo", ]
  end

  if not lane_context[SharedValues::VERSION_NAME]
    version_name_from_tag tag: options[:tag]
  end
  apps
end


lane :get_stored_build_numbers do |options|
  case lane_context[SharedValues::PLATFORM_NAME]
  when :android
    require 'supply'
    require 'supply/options'
    require 'supply/reader'

    ## If called only through build we didn't setup the store
    ## connection.
    if not Supply.config
      _setup_store options
    end
    Supply.config[:package_name] = lane_context[SharedValues::APP_ID]
    begin
      old_track = Supply.config[:track]
      tracks = ["internal", "alpha", "beta", "production"]
	  version_codes = []
	  tracks.each do |track|
        Supply.config[:track] = track
		UI.message "Track #{track}"
		begin
          vc = Supply::Reader.new.track_version_codes || []
		rescue
		  UI.message " .. no version codes for track #{track}"
		else
		  UI.message " .. version codes: #{vc}"
          ## remove nils and add the rest
          version_codes += vc
		end
	  end
      Supply.config[:track] = old_track
    rescue => e
      if e.message.include? 'Package not found'
        version_codes = []
      else
        raise
      end
    end
    versions = version_codes.compact
  when :ios
    FastlaneCore::Globals.verbose = true
    app = Spaceship::ConnectAPI::App.find(
      lane_context[SharedValues::APP_ID]
    )
    builds = Spaceship::ConnectAPI.get_builds(
      filter: { app: app.id },
      sort: "-uploadedDate",
      includes: "preReleaseVersion"
    )
    versions = builds.map { |build| build.version }
  when :web
    ## Nothing to do
    UI.important "No revision support for web. Ignoring."
  else
    UI.user_error!("Unknown platform #{lane_context[SharedValues::PLATFORM_NAME]}")
  end
  UI.message "Store version codes used: #{versions}"
  versions
end




desc "Check signing info are available and setup"
private_lane :_setup_signing do |options|

  case lane_context[SharedValues::PLATFORM_NAME]
  when :android
    ## Fail early if we don't have required info for signing
    check_android_signing_secrets_are_available(
      keystore_base64: options[:keystore_base64],
      keystore_file: options[:keystore_file],
      keystore_password: options[:keystore_password],
      keystore_password_file: options[:keystore_password_file],
    )
  when :ios
    check_ios_signing_secrets_are_available(
      api_key: options[:api_key],
      api_key_path: options[:api_key_path],
      set_spaceship_token: true,
    )
  when :web
    ## Nothing to do
    UI.important "No signing happening for web. Ignoring."
  else
    UI.user_error!("Unknown platform #{lane_context[SharedValues::PLATFORM_NAME]}")
  end

end

desc "Check store access is available and setup"
private_lane :_setup_store do |options|

  case lane_context[SharedValues::PLATFORM_NAME]
  when :android
    check_android_store_secrets_are_available(
      api_key: options[:api_key],
      api_key_path: options[:api_key_path],
    )
  when :ios
    check_ios_store_secrets_are_available(
      api_key: options[:api_key],
      api_key_path: options[:api_key_path],
      set_spaceship_token: true,
    )
  when :web
    ## Nothing to do
    UI.user_error!("No store for platform #{lane_context[SharedValues::PLATFORM_NAME]}")
  else
    UI.user_error!("Unknown platform #{lane_context[SharedValues::PLATFORM_NAME]}")
  end

end



desc "Build release packages and/or screenshots"
private_lane :_build_apps do |options|

  if options[:package].nil? or options[:package]
    _setup_signing options
  end

  if options[:screenshot]
    check_screenshot_config(
      host: options[:host],
      db: options[:db],
      login: options[:login],
      password: options[:password],
      resolution: options[:resolution],
      language: options[:language],
    )
    screenshot_config = lane_context[SharedValues::SCREENSHOT_CONFIG]
  end

  for app in _setup_targets options
    load_app_data app: app
    Actions.lane_context[SharedValues::VERSION_CODE] = nil
    Actions.lane_context[SharedValues::SANDBOX_PATH] = nil

    ## Load the platform dependent packaging
    ## To do so, specify `package:false`
    if options[:package].nil? or options[:package]

      if not lane_context[SharedValues::VERSION_CODE]

        if not options[:rev] and from_publish_store
          vc = (version_code_from_tag tag: options[:tag], rev: 0).to_s
          build_numbers = get_stored_build_numbers options
          build_numbers = build_numbers.select {
            |build_number| build_number.start_with?(vc[0..-3])
          }
          if build_numbers.length != 0
            build_numbers = build_numbers.map {
              |build_number| build_number.to_i
            }
            last_build_number = build_numbers.max
            rev = last_build_number.to_s[-2..].to_i
            if rev >= 98
              UI.user_error! "All revision numbers were taken !"
            end
            rev = rev + 1
          else
            rev = 0
          end
          vc = version_code_from_tag tag: options[:tag], rev: rev
          UI.important ("Inferred first unused rev on store: #{rev}, full build number: #{vc}")
        else
          version_code_from_tag tag: options[:tag], rev: options[:rev]
        end
      end
      package options
    end

    if options[:screenshot]
      if not Actions.lane_context[SharedValues::SANDBOX_PATH]
          sandbox
          customize_app_with_resource unless lane_context[SharedValues::PLATFORM_NAME] == :web
      end
      screenshot_config = lane_context[SharedValues::SCREENSHOT_CONFIG]

      ## run take_screenshots in dry run mode to check if everything is ok
      take_screenshots(
        host: screenshot_config[:host],
        db: screenshot_config[:db],
        login: screenshot_config[:login],
        password: screenshot_config[:password],
        resolution: screenshot_config[:resolution],
        language: screenshot_config[:language],
        force: options[:force],
        dry_run: true,
      )
      if not Actions.lane_context[SharedValues::TAKE_SCREENSHOTS_NEED_RUN]
        UI.message "No screenshot to take for #{app}. Skipping."
        next
      end

      ## If not already built, build web pack
      if not File.exist? "#{Actions.lane_context[SharedValues::SANDBOX_PATH]}/.built-web-pack"
        build_web_pack
      end

      take_screenshots(
        host: screenshot_config[:host],
        db: screenshot_config[:db],
        login: screenshot_config[:login],
        password: screenshot_config[:password],
        resolution: screenshot_config[:resolution],
        language: screenshot_config[:language],
        force: options[:force],
      )
    end
  end

end


lane :screenshot do |options|
  options[:package] = false
  options[:screenshot] = true
  _build_apps options
end


desc "Common platform preparation before build"
private_lane :_prepare_package do |options|

  ## Create sandboxed clone and customize app
  sandbox
  customize_app_with_resource unless lane_context[SharedValues::PLATFORM_NAME] == :web

  ## Fetch, transpiles and pack all web components
  build_web_pack

end


desc "Mobile platform preparation before build"
private_lane :_prepare_mobile_package do |options|
  capacitor_prepare
  version_prepare
end


desc "Build all assets needed for publication"
private_lane :_prepublish do |options|
  from_publish_store = true
  build options
  changelog options if options[:changelog]
  publish_metadata["tag"] = lane_context[SharedValues::VERSION_NAME]
end


desc "Make changelog for current release"
lane :changelog do |options|
  version_name_from_tag tag: options[:tag] unless lane_context[SharedValues::VERSION_NAME]
  gen_changelog
  tag = lane_context[SharedValues::VERSION_NAME]
  if File.exist? "../release/#{tag}/CHANGELOG"
    changelog = File.read("../release/#{tag}/CHANGELOG").lines
    publish_metadata["title"] = (changelog.shift).strip
    publish_metadata["changelog"] = changelog.join
  else
    publish_metadata["title"] = tag
    publish_metadata["changelog"] = false
  end
end


desc "Publish Github"
private_lane :_publish_github do |options|
  _prepublish options unless publish_metadata.entries.length != 0
  _send_github options
end


desc "Publish Store"
private_lane :_publish_store do |options|
  _setup_store options
  _prepublish options unless publish_metadata.entries.length != 0
  send_store options
end


desc "Send Github"
private_lane :_send_github do |options|
  repository_name = options[:github_repository] || ENV["GITHUB_REPOSITORY"]
  if ! repository_name
    UI.message "No `github_repository` nor \$GITHUB_REPOSITORY environment variable set."
    UI.message "Trying to infer default release github repository:"
    begin
      origin_url = sh 'git config --get remote.origin.url'
      UI.message "  Remote origin URL is: #{origin_url}"

      if (match = origin_url.match(/github\.com[:\/]([a-zA-Z0-9-]+\/[a-zA-Z0-9-]+)(\.git)?$/))
        repository_name = match[1]
      end
      UI.message "  Inferring repository name: #{repository_name}"
    rescue
      UI.message "  Can't read remote named 'origin' !"
      UI.important "Can't infer default release repository. Will ask interactively."
    end
  end
  if ! ENV["GITHUB_API_TOKEN"] and ! ENV["GITHUB_TOKEN"]
    UI.user_error! "No \$GITHUB_API_TOKEN, nor \$GITHUB_TOKEN environment variable set."
  end
  ## filter map to contain only `*.apk` and `*.tar.bz2` files
  apks = to_publish.select { |path, label| path.end_with? ".apk" or path.end_with? ".tar.bz2" }
  github_release(
    repository_name: repository_name,
    name: publish_metadata["title"],
    tag_name: publish_metadata["tag"],
    description: publish_metadata["changelog"],
    upload_assets: apks,
    overwrite_existing_assets: options[:overwrite_existing_assets],
    is_draft: options[:draft],
    is_prerelease: publish_metadata["tag"].include?("-rc."),
  )
end


platform :android do

  lane :build do |options|
    _build_apps options
  end

  lane :publish do |options|
    publish_store options
    _publish_github options
  end

  lane :publish_github do |options|
    _publish_github options
  end

  lane :publish_store do |options|
    if options[:screenshot].nil? or options[:screenshot]
      _store_resolutions options
      options[:screenshot] = true
    end
    _publish_store options
  end

  lane :publish_screenshots do |options|
    _setup_store
    _store_resolutions options
    screenshot options
    send_store options
  end

  private_lane :_store_resolutions do |options|
    if options[:resolution]
      UI.user_error!(
        "You should not provide resolutions as they are inferred from " +
        "the platform's store"
      )
    end

    devices = (
      options[:device] || ENV["SCREENSHOT_DEVICE"] || ""
    ).split(",").map { |k| k.to_sym }

    if devices.length != 0
      ## Remove devices from devices_android_resolution keys
      unknown_devices = devices - devices_android_resolution.keys
      if unknown_devices.length != 0
        UI.user_error!(
          "Provided device identifiers are unknown: #{unknown_devices.join(", ")}\n" +
          "  Please on android platform, use one of the following device identifier:\n" +
          "    #{devices_android_resolution.keys.join(", ")}"
        )
      end
      ## Filter out the devices_android_resolution Hash
      devices_android_resolution = (
        devices_android_resolution.entries
          .filter { |k, v| devices.include? k }
      ).to_h
    end
    UI.message "Target device for resolution: #{devices_android_resolution.keys.join(", ")}"

    ## Filter
    options[:resolution] = devices_android_resolution.values.uniq.join(",")
  end

  private_lane :send_store do |options|
    require 'supply'
    require 'supply/options'
    require 'supply/reader'
    require 'digest'

    to_publish.each do |path, label|
      ## accept only "*.aab" paths
      next unless path.end_with? ".aab"
      app = "#{path}".split('/')[-1] \
              .split('_')[0]

      ## XXXvlab: duplicate transformation for android (see version_prepare)
      load_app_data app: app
      build_number = lane_context[SharedValues::VERSION_CODE].to_s

      if (get_stored_build_numbers options).include?(build_number)
        UI.user_error!(
          "Current AAB with same build number (" +
          lane_context[SharedValues::VERSION_CODE].to_s +
          ") is already on store. You must build a new AAB with a " +
          "new build number."
        )
      end
      Supply.config[:aab] = "../#{path}"
      Supply::Uploader.new.perform_upload
    end

    ## Publish screenshots that have been taken
    for app in _setup_targets options
      load_app_data app: app
      Supply.config[:package_name] = lane_context[SharedValues::APP_ID]


      screenshots = Actions.lane_context[SharedValues::TAKE_SCREENSHOTS_REPORT] || {}

      ## keep only screenshots for current app
      screenshots = screenshots.select { |screenshot, metadata|
        metadata[:app] == app
      }

      # if there is at least one screenshot
      if screenshots.length > 0
        UI.message "Uploading screenshots to Google Play"
      else
        UI.message "No screenshots to upload to Google Play"
        next
      end

      existing_images = {}
      client = Supply::Client.make_from_config
      client.begin_edit(package_name: Supply.config[:package_name])
        ## collect image_types
        image_type_languages = screenshots.entries.map { |screenshot, metadata|
          ["#{devices_android_resolution.key(metadata[:resolution])}Screenshots", metadata[:language]]
        }.uniq

        image_type_languages.each do |image_type, language|
          if options[:force_upload]
            UI.important("Clearing all screenshots of #{app} for #{image_type} in #{language}.")
            client.clear_screenshots(image_type: image_type, language: language)
            existing_images[[image_type, language]] = []
          else
            UI.message("Checking #{image_type} #{language} checksums on google store...")
            ## fetch existing image urls
            existing_images[[image_type, language]] = client.fetch_images(image_type: image_type, language: language)
          end
        end

      screenshots.entries.each do |screenshot, metadata|
        image_type = "#{devices_android_resolution.key(metadata[:resolution])}Screenshots"
        image_path = "../#{screenshot}"

        sha256 = Digest::SHA256.file(image_path).hexdigest
        if existing_images[[image_type, metadata[:language]]].map(&:sha256).include?(sha256)
          UI.important("  Skip upload of #{app} screenshot #{image_path} as remote sha256 matches.")
          UI.message("    use force_upload:true to force deletion of previous screenshots.")
          next
        end

        UI.message "  Add upload of #{screenshot}"
        client.upload_image(
          ## append current working directory to the screenshot path
          image_path: image_path,
          image_type: image_type,
          language: metadata[:language],
        )
      end
      client.commit_current_edit!
      UI.success("Successfully finished the #{screenshots.length} #{app}'s screenshots upload to Google Play")
    end
  end

  private_lane :prepare_mobile_package do |options|
    _prepare_mobile_package
  end

  private_lane :package do |options|

    app = lane_context[SharedValues::APP_NAME]
    version_name = lane_context[SharedValues::VERSION_NAME]
    version_code = lane_context[SharedValues::VERSION_CODE]

    file_name = "#{app}_#{version_name}_#{version_code}"
    bundle_file_name = "#{file_name}.aab"
    package_file_name = "#{file_name}.apk"
    result_dir="release/#{version_name}"
    result_file_label="#{app} - #{version_name} (#{version_code})"
    if File.exist? "../#{result_dir}/#{bundle_file_name}"
      if ! options[:force]
        UI.important "Release file of #{app} already exists in '#{result_dir}/#{bundle_file_name}'."
        UI.message "  Ignoring build. If you want to overwrite it, provide 'force:true' as an argument."
        to_publish["#{result_dir}/#{bundle_file_name}"] = "Android Bundle (AAB) - #{result_file_label}"
        if File.exist? "../#{result_dir}/#{package_file_name}"
          to_publish["#{result_dir}/#{package_file_name}"] = "Android App (APK) - #{result_file_label}"
        end
        next
      else
        UI.important "Existing release file for #{app} #{result_dir}/#{bundle_file_name} will be overwritten."
      end
    end

    _prepare_package
    prepare_mobile_package

    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "#{Actions.lane_context[SharedValues::SANDBOX_PATH]}/android",
      properties: {
        ## Versioning
        "android.injected.version.code" => version_code,
        "android.injected.version.name" => version_name,

        ## Signing
        "android.injected.signing.store.file" => lane_context[SharedValues::ANDROID_KEYSTORE],
        "android.injected.signing.store.password" => ENV["RELEASE_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => lane_context[SharedValues::ANDROID_KEY_ALIAS],
        "android.injected.signing.key.password" => ENV["RELEASE_KEY_PASSWORD"],
      },
      print_command: false,
    )

    FileUtils.mkdir_p "../#{result_dir}"
    FileUtils.mv(lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH],
                 "../#{result_dir}/#{bundle_file_name}")
    to_publish["#{result_dir}/#{bundle_file_name}"] = "Android Bundle (AAB) - #{result_file_label}"

    gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: "#{Actions.lane_context[SharedValues::SANDBOX_PATH]}/android",
      properties: {
        ## Versioning
        "android.injected.version.code" => version_code,
        "android.injected.version.name" => version_name,

        ## Signing
        "android.injected.signing.store.file" => lane_context[SharedValues::ANDROID_KEYSTORE],
        "android.injected.signing.store.password" => ENV["RELEASE_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => lane_context[SharedValues::ANDROID_KEY_ALIAS],
        "android.injected.signing.key.password" => ENV["RELEASE_KEY_PASSWORD"],
      },
      print_command: false,
    )

    FileUtils.mv(lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
                 "../#{result_dir}/#{package_file_name}")
    to_publish["#{result_dir}/#{package_file_name}"] = "Android App (APK) - #{result_file_label}"

  end


end


platform :ios do

  lane :build do |options|
    ## Lokavaluto's team id is hard-written here for now
    team_id "25AZX5J5PX"

    _build_apps options
  end

  lane :publish do |options|
    publish_store options
  end

  lane :publish_github do |options|
    _publish_github options
  end

  lane :publish_store do |options|
    if options[:screenshot].nil? or options[:screenshot]
      _store_resolutions options
      options[:screenshot] = true
    end
    _publish_store options
  end

  private_lane :_store_resolutions do |options|
    if options[:resolution]
      UI.user_error!(
        "You should not provide resolutions as they are inferred from " +
        "the platform's store"
      )
    end

    devices = (
      options[:device] || ENV["SCREENSHOT_DEVICE"] || ""
    ).split(",").map { |k| k.to_sym }

    if devices.length != 0
      unknown_devices = devices - devices_ios_resolution.keys
      if unknown_devices.length != 0
        UI.user_error!(
          "Provided device identifiers are unknown: #{unknown_devices.join(", ")}\n" +
          "  Please, on ios platform, use one of the following device identifier:\n" +
          "    #{devices_ios_resolution.keys.join(", ")}"
        )
      end
      ## Filter out the devices_ios_resolution Hash
      devices_ios_resolution = (
        devices_ios_resolution.entries
          .filter { |k, v| devices.include? k }
      ).to_h
    end
    UI.message "Target device for resolution: #{devices_ios_resolution.keys.join(", ")}"

    ## Filter
    options[:resolution] = devices_ios_resolution.values.uniq.join(",")
  end

  lane :publish_screenshots do |options|
    ## Check if `deliver` has all required authentication stuff ready
    _setup_store
    _store_resolutions options
    screenshot options
    send_store options
  end

  private_lane :send_store do |options|
    ## Publish package that have been built
    to_publish.each do |path, label|
      app = "#{path}".split('/')[-1] \
              .split('_')[0]

      ## XXXvlab: duplicate transformation for iOS (see version_prepare)
      load_app_data app: app
      build_number = lane_context[SharedValues::VERSION_CODE].to_s

      if (get_stored_build_numbers options).include?(build_number)
        UI.user_error!(
          "Current IPA with same build number (" +
          lane_context[SharedValues::VERSION_CODE].to_s +
          ") is already on testflight. You must build a new IPA with a " +
          "new build number."
        )
      end
      upload_to_testflight(
        app_identifier: lane_context[SharedValues::APP_ID],
        ipa: path,
      )
    end

    ## Publish screenshots that have been taken
    for app in _setup_targets options
      load_app_data app: app

      send_store_screenshots_appstore(
        devices_ios_resolution: devices_ios_resolution
      )
    end
  end

  private_lane :prepare_mobile_package do |options|

    require 'xcodeproj'
    project_root = "#{Actions.lane_context[SharedValues::SANDBOX_PATH]}/ios/App/"
    project_path = project_root + "App.xcodeproj"
    project = Xcodeproj::Project.open(project_path)
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGN_STYLE'] = "Manual"
        config.build_settings['CODE_SIGN_IDENTITY'] = "Apple Distribution"
        config.build_settings['DEVELOPMENT_TEAM'] = ENV['FASTLANE_TEAM_ID']
        config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = "match AppStore #{lane_context[SharedValues::APP_ID]}"
      end
    end
    project.save

    plist_path = project_root + "App/Info.plist"
    set_info_plist_value(path: plist_path, key: "ITSAppUsesNonExemptEncryption", value: "false")

    _prepare_mobile_package
  end

  private_lane :package do |options|

    app = lane_context[SharedValues::APP_NAME]
    version_name = lane_context[SharedValues::VERSION_NAME]
    version_code = lane_context[SharedValues::VERSION_CODE]

    app_id = lane_context[SharedValues::APP_ID]


    file_name = "#{app}_#{version_name}_#{version_code}"
    bundle_file_name = "#{file_name}.ipa"
    result_dir="release/#{version_name}"
    result_file_label="#{app} - #{version_name} (#{version_code})"
    if File.exist? "../#{result_dir}/#{bundle_file_name}"
      if ! options[:force]
        UI.important "Release file of #{app} already exists in '#{result_dir}/#{bundle_file_name}'."
        UI.message "  Ignoring build. If you want to overwrite it, provide 'force:true' as an argument."
        to_publish["#{result_dir}/#{bundle_file_name}"] = "iOS App Store Package (IPA) - #{result_file_label}"
        next
      else
        UI.important "Existing release file for #{app} #{result_dir}/#{bundle_file_name} will be overwritten."
      end
    end

    _prepare_package
    prepare_mobile_package

    Dir.chdir(Actions.lane_context[SharedValues::SANDBOX_PATH]) do
      UI.message sh('git diff ios', print_command_output: false)
    end

    ## Create temporary keychain for CI
    setup_ci if ENV['CI']
    match(type: "appstore", app_identifier: app_id, readonly: true)

    build_app(
      workspace: "#{Actions.lane_context[SharedValues::SANDBOX_PATH]}/ios/App/App.xcworkspace",
    )

    FileUtils.mkdir_p "../#{result_dir}"
    FileUtils.mv(lane_context[SharedValues::IPA_OUTPUT_PATH],
                 "../#{result_dir}/#{bundle_file_name}")
    to_publish["#{result_dir}/#{bundle_file_name}"] = "iOS App Store Package (IPA) - #{result_file_label}"

  end

end

platform :web do

  lane :publish do |options|
    _publish_github options
  end

  lane :build do |options|
    version_name_from_tag tag: options[:tag]

    lane_context[SharedValues::APP_NAME] = "monujo"
    ## Load the platform dependent packaging
    package options
  end

  lane :publish_github do |options|
    _publish_github options
  end

  lane :send_store do |options|
    UI.user_error! "send_store not yet implemented for #{lane_context[SharedValues::PLATFORM_NAME]}!"
  end

  private_lane :package do |options|

    app = lane_context[SharedValues::APP_NAME]
    tag = lane_context[SharedValues::VERSION_NAME]

    file_name = "#{app}_#{tag}"
    package_file_name = "#{file_name}.tar.bz2"
    result_dir="release/#{tag}"
    if File.exist? "../#{result_dir}/#{package_file_name}"
      if ! options[:force]
        UI.important "Release file of #{app} already exists in '#{result_dir}/#{package_file_name}'."
        UI.message "  Ignoring build. If you want to overwrite it, provide 'force:true' as an argument."
        to_publish["#{result_dir}/#{package_file_name}"] = "Web (tar.bz2) - #{tag}"
        next
      else
        UI.important "Existing release file for #{app} #{result_dir}/#{package_file_name} will be overwritten."
      end
    end

    _prepare_package

    FileUtils.mkdir_p "../#{result_dir}"
    sh ("( cd \"#{Actions.lane_context[SharedValues::SANDBOX_PATH]}/dist\" ; tar cj . ) > " +
        "\"../#{result_dir}/#{package_file_name}\"")

    to_publish["#{result_dir}/#{package_file_name}"] = "Web (tar.bz2) - #{tag}"

  end
end
